refactor: spectator-camera
benevolent-games/toolbox pull request #27
Opened 2023-03-10 23:13 UTC by zenkyuv

2023-03-13 16:54 UTC, chase-moskal requested changes
on closer inspection, this spectator cam is quite tangled, confusing, and twisted.

let's rewrite it, so it's more direct, straightforward, and prefers to use more pure functions where it makes sense.

2023-03-13 16:54 UTC, chase-moskal commented on s/babylon/camera/spectator-camera.ts
> +		walk, scene, engine, nubContext, renderLoop, lookSensitivity: {mouse}, startPosition
let's reshape spectator cam into two smaller parts:

```js
// - creates the camera apparatus
// - knows about babylon
// - returns functions to add look/move values
const fly = make_fly_camera({scene, position})

// - listens for nub events and looks at effects
// - calculates and applies look and move
// - has no knowledge of babylon
// - has no knowledge of the fly camera
integrate_move_and_look({
  nub_context,
  render_loop,
  sensitivity: {
    pointer: 1 / 500,
    stick: 1 / 50,
  },
  speed: {
    creep: 0.3,
    walk: 1,
    sprint: 3,
  },
  controls: {
    add_look: fly.add_look,
    add_move: fly.add_move,
  },
})
```

2023-03-13 16:54 UTC, chase-moskal commented on s/babylon/camera/spectator-camera.ts
> +		const position = new Vector3(...startPosition)
i believe this is the wrong place to apply the startPosition

we actually want to set this on `transformA`

2023-03-13 16:54 UTC, chase-moskal commented on s/babylon/camera/spectator-camera.ts
> +					})
this cluster of code is very confusing

following these functions, it feels tangled up -- i think this area and its extracted functions and their dependency functions have become knotted up, and should be rewritten

2023-03-13 16:54 UTC, chase-moskal commented on s/babylon/camera/spectator-camera.ts
>  	})
something about the walker smells off -- i think this should be rewritten

2023-03-13 16:54 UTC, chase-moskal commented on s/babylon/camera/utils/look-add.ts
> +}
let's make this a pure function without side-effect

it should accept a look vector and an addition vector, and return a new result vector -- without writing any side-effect

2023-03-13 16:54 UTC, chase-moskal commented on s/babylon/camera/utils/on-camera-movement.ts
> +export function onCameraMovement({
this isn't a callback function, so let's remove the `on` prefix.

also, it's confusing what this actually does compared to `updateCameraMovement` exactly -- let's choose better names to distinguish these

2023-03-13 16:54 UTC, chase-moskal commented on s/babylon/camera/utils/on-camera-rotate.ts
> +export function onCameraRotate({getUpdateStarters, addMouseforce, updateCameraRotation}: {
similarly remove the `on` prefix and choose a better name

2023-03-13 16:54 UTC, chase-moskal commented on s/babylon/camera/utils/on-camera-rotate.ts
> +		updateCameraRotation()
this line about updateCameraRotation seems very suspicious -- it must be relying on side-effects, so it's modifying things -- we need to rewrite this to be more pure

2023-03-13 16:54 UTC, chase-moskal commented on s/babylon/camera/utils/transform-rotate.ts
> +export function transformRotate(currentLook: v2.V2, transformA: TransformNode, transformB: TransformNode) {
maybe a better name like `apply_look_onto_gimbal(look, gimbal)`

and maybe we package up the two transforms and call that a "gimbal" which i believe is accurate, or somewhat accurate

```ts
export type Gimbal = {
  a: TransformNode
  b: TransformNode
}
```

2023-03-13 16:54 UTC, chase-moskal commented on s/babylon/camera/spectator-camera.ts
> +			getUpdateStarters: () => ({getForce, transformB}),
there's something very smelly about this `getUpdateStarters` getter

it's some kind of confusing indirection -- let's straighten this out, eliminate the getter, and just provide the arguments that functions need more directly

2023-03-16 22:46 UTC, chase-moskal approved these changes
hey, most of this is good stuff.

i'm going to merge this, and make some improvements of my own.

2023-03-16 22:46 UTC, chase-moskal commented on s/babylon/camera/utils/move-camera.ts
this function is literally insane :rofl: 

if you examine its purpose, you'll find it has no reason to exist -- we don't need a function to help us call that function.

2023-03-16 22:46 UTC, chase-moskal commented on s/babylon/camera/utils/rotate-camera.ts
this function is also fundamentally crazy.

if we already have the addMouseforce function, and the movement -- why do we need rotateCamera to call it?

2023-03-16 22:46 UTC, chase-moskal commented on s/demo.ts
i think the separation between the fly_camera and the spectator is good

but we should probably think of better names

2023-03-16 23:29 UTC, zenkyuv commented on s/babylon/camera/utils/move-camera.ts
i know it looks weird to call literally one thing in this function, but i though maybe it will be more clear that the purpose is to move camera by adding some move force to it xd

2023-03-17 20:57 UTC, merged